# Generated by Django 4.2.1 on 2023-05-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_conditions_delete_weatherconditions_city_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="conditions",
            field=models.ManyToManyField(to="main.conditions"),
        ),
    ]
