# Generated by Django 4.2.1 on 2023-05-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_city_conditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather", models.CharField(max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
