# Generated by Django 4.2.1 on 2023-05-28 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_weatherentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeatherEntry",
        ),
    ]
