# Generated by Django 4.2.1 on 2023-05-28 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_delete_weatherentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("wind", models.FloatField()),
                ("condition", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=100)),
                ("last_updated", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.city"
                    ),
                ),
            ],
        ),
    ]
