FROM python:3.10-bullseye
ENV PYTHONUNBUFFERED 1
WORKDIR /app
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
CMD /wait && python manage.py migrate && python manage.py runserver "0.0.0.0:8000"

# # django-crontab logfile
# RUN mkdir /cron
# RUN touch /cron/django_cron.log
# EXPOSE 8000
# CMD service cron start && python manage.py runserver 0.0.0.0:8000